# Getting Started

Let's check our Python version

In [ ]:
!python --version

Python 3.8.15


# Strings

We can print a simple string

In [ ]:
print('hello world')

hello world


Comments use #

In [ ]:
# comment 1
print('not a comment') # comment 2
# comment 3

not a comment


Even when we don't print, we can see a returned value.

In [ ]:
'hello world' # Google colab uses "IPython" AKA "Jypyter" notebooks which print return values from separate "blocks" AKA "cells".
# The "blocks" terminology should be avoided in serious technical discussions so as not to conflate these notebook sections with
# computer programming blocks https://en.wikipedia.org/wiki/Block_(programming).

'hello world'

Only the last returned value..

In [ ]:
'hello'
'world'

'world'

We can check variable types with the type() function.

In [ ]:
a = 'b'
print(a) # we can evaluate and print variables with print()
type(a)

b


str

In [ ]:
a = "b" # double quotes also work
print(a)
type(a)

b


str

Docstrings

In [ ]:
a = """b""" # triple quotes also work
print(a)
type(a)

b


str

In [ ]:
a = """b
is now a
multi-line
string."""
print(a)
type(a)

b
is now a
multi-line
string.


str

In [ ]:
a = """b \
is now a \
single-line \
string."""
print(a)
type(a)

b is now a single-line string.


str

Single quotes can't be used for multi-line strings

In [ ]:
a = "b
ut this is
not valid syntax"

SyntaxError: ignored

In [ ]:
a = "b\
ut this is \
ok"
print(a)
type(a)

but this is ok


str

E is not a defined variable

In [ ]:
type(E)

NameError: ignored

# Numerics

In [ ]:
a = 0.1
b = 0.5
print(a)
print(b)
print(a == b)

0.1
0.5
False


In [ ]:
print(a is b) # tests whether a and b are the same object

False


In [ ]:
c = 0.1
print(a)
print(c)
print(a is c)
print(a == c)

0.1
0.1
False
True


In [ ]:
c = a
print(a is c)

True


In [ ]:
print(a)
print(b)

0.1
0.5


In [ ]:
print(type(a))
print(type(b))
print(type(a) is type(b))

<class 'float'>
<class 'float'>
True


In [ ]:
a = 1
type(a)

int

In [ ]:
a = 1.01
type(a)

float

In [ ]:
a = b'\x00\x10'
type(a)

bytes

In [ ]:
print(f'a == 16? {a == 16}')
print(f'a = {a}')
print(f'len(a) = {len(a)}')
print(f'a[0] = {a[0]} = {bin(a[0])}')
print(f'a[1] = {a[1]} = {bin(a[1])}')


a == 16? False
a = b'\x00\x10'
len(a) = 2
a[0] = 0 = 0b0
a[1] = 16 = 0b10000


Endianness

In [ ]:
# endianness is the byte order (big or little)
c = int.from_bytes(a,"big")     # big-endian means most significant byte is at lowest index
print(f'c == 16? {c == 16}')
d = int.from_bytes(a,"little")  # little-endian means most significant byte is at the highest index
print(f'd == {d}')

c == 16? True
d == 4096


In [ ]:
a = 100
print(f'1. a is equal to {a}')                        # the f-strings mechanism is how we're going to interpolate strings here
print("2. a is equal to",a)                           # space character is the default separator
print("3. a is equal to ",a,sep="")                   # we can set the separator with sep=
print("4. a is equal to {a_value}".format(a_value=a)) # we can name parameters and use .format()
print("5. a is equal to %s" % a)                      # the old way

1. a is equal to 100
2. a is equal to 100
3. a is equal to 100
4. a is equal to 100
5. a is equal to 100


Numeric operations

In [ ]:
print(2 + 3)  # addition
print(2 * 3)  # multiplication
print(2 - 3)  # subtraction
print(2 / 3)  # division (INTEGER DIVISON IN PYTHON 2)
print(2 // 3) # integer division
print(2 ** 3) # power
print(2 % 3)  # modulus

5
6
-1
0.6666666666666666
0
8
2


Python doesn't have the technology to divide by zero

In [ ]:
z = 1/0

ZeroDivisionError: ignored

In [ ]:
z = 12
print(z)
z += 5
print(z)
z /= 5
print(z)
z **= 2
print(z)

12
17
3.4
11.559999999999999


Sometimes we have to use both single and double quotes

In [ ]:
z = float('inf')
z /= 2
print(z)
z /= z
print(z)
print(f'is z nan? {z != z}')

print(f"is nan equal to nan? {float('nan') == float('nan')}") #note single and double quotes are required here

inf
nan
is z nan? True
is nan equal to nan? False


int() is used to create int from other types... similar functions exist for other types

In [ ]:
z = float(5.5)
type(z)

float

In [ ]:
b = int(z)
type(b)

int

In [ ]:
print(int(5.5))

5


In [ ]:
print(int(5.9))

5


In [ ]:
print(int(6.0000000000001))

6


In [ ]:
print(int(-5.5)) # rounding toward 0

-5


# Booleans

In [ ]:
tx = True
fx = False
type(tx)

bool

In [ ]:
print(tx^fx) # bitwise XOR

True


In [ ]:
print(tx != fx) # logical XOR

True


In [ ]:
print(0^0)
print(0^1)
print(1^0)
print(1^1)

0
1
1
0


In [ ]:
print(0 != 0)
print(0 != 1)
print(1 != 0)
print(1 != 1)

False
True
True
False


In [ ]:
print(tx or fx)

True


In [ ]:
print(0 or 0)
print(0 or 1)
print(1 or 0)
print(1 or 1)

0
1
1
1


In [ ]:
print(tx and fx)

False


In [ ]:
print(0 and 0)
print(0 and 1)
print(1 and 0)
print(1 and 1)

0
0
0
1


In [ ]:
print(not tx)
print(not fx)

False
True


In [ ]:
print(not 1)
print(not 0)

False
True


# Lists

In [ ]:
z = [1,2]
type(z)

list

In [ ]:
len(z)

2

In [ ]:
print(z)
print(bool(z))

[1, 2]
True


In [ ]:
z[0:2]

[1, 2]

In [ ]:
z[0:1]

[1]

In [ ]:
z[1:2]

[2]

In [ ]:
print(f'z[0] == {z[0]}')
print(f'z[1] == {z[1]}')

z[0] == 1
z[1] == 2


index -0 is the same as 0

In [ ]:
print(f'z[-0] == {z[-0]}')

z[-0] == 1


In [ ]:
print(f'z[-1] == {z[-1]}') # same as z[1]
print(f'z[-2] == {z[-2]}') # same as z[0]

z[-1] == 2
z[-2] == 1


z doesn't have an index after 1

In [ ]:
print(f'z[2] == {z[2]}')

IndexError: ignored

z also doesn't have an index before 0

In [ ]:
print(f'z[-3] == {z[-3]}')

IndexError: ignored

In [ ]:
x = [1,2,3,4,5,6,7,8,9,10]
print(f'x[0:5:2] is {x[0:5:2]}')
print(f'x[0:10:3] is {x[0:10:3]}')

x[0:5:2] is [1, 3, 5]
x[0:10:3] is [1, 4, 7, 10]


In [ ]:
z = [1,2]
x = [1,2]
print(f'z == x? {z == x}')
x[0] = 100
print(f'z == x? {z == x}')
print(f'x == {x}')

z == x? True
z == x? False
x == [100, 2]


# Tuples

In [ ]:
z = (1,2)
type(z)

tuple

In [ ]:
z = (1)
type(z)

int

In [ ]:
z = (1,)
type(z)

tuple

In [ ]:
x = (1,2)
print(f'z == x? {z == x}')

z == x? False


In [ ]:
z = (1,2,2,2)
print(z)

(1, 2, 2, 2)


In [ ]:
x[0] = 100

TypeError: ignored

# Dictionaries

In [ ]:
A = dict(key1=1, key2=2)
A["key3"] = 300
Y = A["key2"] # double quotes
Z = A["key3"]
print(Y)
print(Z)

2
300


In [ ]:
example_dictionary = {'key1':'value1', 'key2':'value2', 1000:'value_9000'} # curly braces may be used instead of dict()
print(example_dictionary['key1']) # single quotes
print(example_dictionary[1000])

value1
value_9000


In [ ]:
example_dictionary['key3'] = 7
example_dictionary['12345'] = 'seven'
print(example_dictionary['key3'])
print(example_dictionary['12345'])

7
seven


In [ ]:
print(example_dictionary['key4'])

KeyError: ignored

# Sets

In [ ]:
a = set([1,2,2,2])
b = set([1,2])
a == b

{1, 2}


In [ ]:
example_set = {'value1', 'value2',4,5.5}
print(3 in example_set)
example_set.add(3)
print(3 in example_set)
print(5.5 in example_set)

False
True
True


In [ ]:
example_set.add('value1') # idempotency
example_set.add(3)
example_set.add(3)
example_set.add(3)

In [ ]:
print(example_set)

{3, 'value2', 5.5, 4, 'value1'}


In [ ]:
example_set.remove(3)
print(example_set)

{'value2', 5.5, 4, 'value1'}


# Loops

In [ ]:
z = 5
while z < 10: # loop invariant
  print(z)
  z = z + 1

5
6
7
8
9


In [ ]:
z = range(0)
print(f'type(z) == {type(z)}')
print(f'range(5) == {range(5)}')

type(z) == <class 'range'>
range(5) == range(0, 5)


In [ ]:
for i in range(3):
  print(i)

0
1
2


In [ ]:
for i in range(10):
  if i % 2 == 0:
    print(i)

0
2
4
6
8


In [ ]:
for i in range(10):
  if i % 2 == 0:
    print(i)
  elif i % 3 == 0:
    print(i * 2)
  else:
    print("--")

0
--
2
6
4
--
6
--
8
18


Comprehensions

In [ ]:
# list "comprehension" is an example of "pythonic" thinking
[print(i) for i in range(10) if i % 2 == 0]

0
2
4
6
8


[None, None, None, None, None]

In [ ]:
# the list of "None" is returned above because print() prints but does not return a value
print([i for i in range(10) if i % 2 == 0])

[0, 2, 4, 6, 8]


In [ ]:
# chain elses in a comprehension for conditional logic
print([i if i % 2 == 0 else i * 2 if i % 3 == 0 else "--" for i in range(10)])

[0, '--', 2, 6, 4, '--', 6, '--', 8, 18]


Control Flow

In [ ]:
for x in range(10):
    if x == 8:
        print("8!")
        continue
    print("not 8!")


not 8!
not 8!
not 8!
not 8!
not 8!
not 8!
not 8!
not 8!
8!
not 8!


# Functions

In [ ]:
# a function with a return value and zero parameters
def function1():
  return 1

z = function1()

print(f'function1 returned {z}')

function1 returned 1


In [ ]:
#Some languages might refer to code like this as a "procedure" because it does not appear to return a value.
#In python, this returns None and is correctly referred to as a "function".
def function2():
  print("hello2")

x = 100

print(f'x is set to {x}')

x = function2()

print(f'function2 returned {x}')

x is set to 100
hello2
function2 returned None


In [ ]:
# function with a parameter
def function3(parameterA):
  z_string = f'ZZZ - {parameterA} - ZZZ'
  return z_string

argumentA = "im sleep" # the argument is "im sleep"

output = function3(argumentA) # we would say the argument is "passed" to the function

print(output)

ZZZ - im sleep - ZZZ


In [ ]:
def square_if_odd(n):
    if n % 2 != 0:
        return n * n
    return n

print(square_if_odd(2))
print(square_if_odd(3))
print(square_if_odd(4))
print(square_if_odd(5))

2
9
4
25


In [ ]:
def add_three_numbers(a,b,c):
  return a + b + c

add_three_numbers(1,2,10)

13

In [ ]:
def add_two_or_three_numbers(a,b,c=0): #functions allow positional and optional keyword arguments
  return a + b + c

print(add_two_or_three_numbers(5,20, 1))
print(add_two_or_three_numbers(5,20))

26
25


An error occurs if functions are called without valid arguments

In [ ]:
print(add_two_or_three_numbers(5))

TypeError: ignored

In [ ]:
def mult_and_sub(a,b):
  return a * b - a - b

p = [1]
q = [3]
z = map(mult_and_sub,p,q)

print(f'first call returns {list(z)}')

p = [1,2,-1]
q = [3,4,10]
z = map(mult_and_sub,p,q)

print(f'second call returns {list(z)}')

first call returns [-1]
second call returns [-1, 2, -19]


# The random module

In [ ]:
import random

def randomly_select_number(a,b,c):
  return random.choice([a,b,c])

randomly_select_number(1,2,10)

1

In [ ]:
help(random)

In [ ]:
from random import randint as ri
a = 1
b = 100
print(f'a random number from {a} to {b}: {ri(a,b)}')

a random number from 1 to 100: 90


In [ ]:
random.random()

0.9231546252181674

In [ ]:
random.seed(123)
print(random.random())
print(random.random())
print(random.random())

0.052363598850944326
0.08718667752263232
0.4072417636703983


In [ ]:
import random as rnd
print(f'first call returns {rnd.random()}')

import random as abcdef123
print(f'second call returns {abcdef123.random()}')

print(f'third call returns {random.random()}')

first call returns 0.09276456137849509
second call returns 0.14217506443150107
third call returns 0.7900718443588016


# The re module

In [ ]:
import re
txt = "this is an example of a multi-character string with several words for \
the regular expression package demonstration in a simple introduction to python\
 tutorial without paying attention to grammar"
pattrn = re.compile("[\s+]([a-zA-Z]+ing)[\s+]([a-zA-Z]+)",flags=0)
for match in pattrn.finditer(txt):
  print(match.groups())
  print(match.group(1))

('string', 'with')
string
('paying', 'attention')
paying


In [ ]:
help(re)

# File I/O

In [ ]:
file_name = "text_file.txt"
file_pointer = open(file_name,'w')
print(f"is it closed? {file_pointer.closed}")
file_pointer.close()
print(f"is it closed? {file_pointer.closed}")

is it closed? False
is it closed? True


In [ ]:
new_file = open('example.txt','w')
new_file.write("this is sample text!")
new_file.close()

existing_file = open('example.txt','r') 
x = existing_file.readline()
existing_file.close()

print(f'x is now set to {x}')

print(new_file.closed)
print(existing_file.closed)

x is now set to this is sample text!
True
True


In [ ]:
file_pointer = open(file_name,'w')
try:
    file_pointer.write("aaaaaaaaa\nbbbbbbbbbb\nccccccccccc\n")
finally:
    file_pointer.close()

In [ ]:
file_pointer = open(file_name,'r')
try:
  print(f'first line = {file_pointer.readline()}')
finally:
  file_pointer.close()

first line = aaaaaaaaa



In [ ]:
import sys # catch and print file I/O exceptions

file_pointer = open(file_name,'r')
try:
  print(f'file text = {file_pointer.readlines()}')
  file_pointer.write("zzzzzzzz!!!!!!")
except:
  print(f"an exception occurred: {sys.exc_info()[0]}...")
finally:
  file_pointer.close()
  print(f'closed the {file_name} file pointer')

file text = ['aaaaaaaaa\n', 'bbbbbbbbbb\n', 'ccccccccccc\n']
an exception occurred: <class 'io.UnsupportedOperation'>...
closed the text_file.txt file pointer


In [ ]:
# with encapsulates the open() function and 
# can be used instead of the try/finally syntax above
with open(file_name, 'r') as file_pointer2:
  print(file_pointer2.readline())
  print(file_pointer2.readline())

print(f"closed? {file_pointer2.closed}")

aaaaaaaaa

bbbbbbbbbb

closed? True


with will show exceptions

In [ ]:
with open(file_name, 'r') as file_pointer3:
  print(file_pointer3.readline())
  print(file_pointer3.readline())
  file_pointer3.write("zzzzzz")



aaaaaaaaa

bbbbbbbbbb



UnsupportedOperation: ignored

and with will still close file pointers

In [ ]:
print(f"closed? {file_pointer3.closed}")

closed? True


# The NumPy module

In [ ]:
import numpy as np # using "np" for the numpy package is a common convention

array1 = np.array([0,1,2])
type(array1)

numpy.ndarray

there's plenty of online documentation at https://numpy.org/

In [ ]:
help(np)

In [ ]:
array2 = np.array([[10,20,30],[40,50,60]])
type(array2)

numpy.ndarray

In [ ]:
print(array1.shape)
print(array2.shape)

(3,)
(2, 3)


In [ ]:
print(array1[0:2])
print(array1[0:3])

[0 1]
[0 1 2]


We can do this

In [ ]:
print(array1[0:100])

[0 1 2]


We can't actually access those indices

In [ ]:
print(array1[100])

IndexError: ignored

In [ ]:
print(array2)

[[10 20 30]
 [40 50 60]]


In [ ]:
print(array2[1,1:3])

[50 60]


In [ ]:
array3 = np.transpose(array2)

In [ ]:
print(array3)

[[10 40]
 [20 50]
 [30 60]]


In [ ]:
print(array3.shape)

(3, 2)
